plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 2020

rules: {
  "no-underscore-dangle": [2, { "allow": ["__filename", "__dirname"] }],
	"no-console": "off",
	"import/extensions": "off"
}
